### ISSUE TITLE
trade-client is not public and breaks installation

### ISSUE THREAD

**Issue by bobbywilson0** [makerdao/market-maker-stats#5]
The sub-module added [here](https://github.com/makerdao/market-maker-stats/commit/3b0091f43076886273ba5efac46694cfb2432874) seems to break the installation as the trade-client repo doesn't seem to be public at this time.

**Comment by WyseNynja** [comment]
Is https://github.com/LiquidityProviders/trade-service also a private repo? It’s a 404 for me so I’m guessing so.

**Comment by reverendus** [comment]
@WyseNynja yes, it is

**Comment by reverendus** [comment]
Regarding the original issue, we will at some point split this repo into two. The public one will not have dependency on `trade-client` anymore.

**Comment by reverendus** [comment]
Fixed!
